// <auto-generated />
using System;
using DCAS_PracticalExam.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DCAS_PracticalExam.Migrations
{
    [DbContext(typeof(PracticalExamContext))]
    [Migration("20220314154243_FirtsCheck")]
    partial class FirtsCheck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DCAS_PracticalExam.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DCAS_PracticalExam.Models.CPRAssessmentEvaluationFields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assessor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor1Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Assessor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor2Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CRMRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsStep1")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep10")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep2")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep3")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep4")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep5")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep6")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep7")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep8")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep9")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CPRAssessmentEvaluationFields");
                });

            modelBuilder.Entity("DCAS_PracticalExam.Models.EvaluationInstructorsFields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assessor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRMRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvaluationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ExaminerSign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalQualifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question10Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question1Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question1Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question2Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question2Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question3Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question3Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question4Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question4Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question5Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question5Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question6Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question6Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question7Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question7Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question8Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question8Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question9Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EvaluationInstructorsFields");
                });

            modelBuilder.Entity("DCAS_PracticalExam.Models.MedicalAssessmentEvaluationFields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assessor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor1Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Assessor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor2Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CRMRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CriteriaCheck1")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck2")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck3")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck4")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck5")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck6")
                        .HasColumnType("bit");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsStep1")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep10")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep11")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep12")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep13")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep14")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep15")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep16")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep17")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep18")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep19")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep2")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep20")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep21")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep22")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep23")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep24")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep25")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep26")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep27")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep3")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep4")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep5")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep6")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep7")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep8")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep9")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MedicalAssessmentEvaluationFields");
                });

            modelBuilder.Entity("DCAS_PracticalExam.Models.TraumaAssessmentEvaluationFields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assessor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor1Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Assessor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Assessor2Sign")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CRMRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CriteriaCheck1")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck2")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck3")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck4")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck5")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck6")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck7")
                        .HasColumnType("bit");

                    b.Property<bool>("CriteriaCheck8")
                        .HasColumnType("bit");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsStep1")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep10")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep11")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep12")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep13")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep14")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep15")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep16")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep17")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep18")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep19")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep2")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep20")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep21")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep22")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep23")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep24")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep25")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep26")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep27")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep28")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep29")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep3")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep30")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep31")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep32")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep33")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep34")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep35")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep36")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep37")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep38")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep39")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep4")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep40")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep5")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep6")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep7")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep8")
                        .HasColumnType("int");

                    b.Property<int>("PointsStep9")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TraumaAssessmentEvaluationFields");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DCAS_PracticalExam.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DCAS_PracticalExam.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCAS_PracticalExam.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DCAS_PracticalExam.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
